#!/usr/bin/env bash 

export PREACH_MACHINE=$1
export PREACH_NODE_NAME=$2
export LOGDIR=$3
export EPMD=$4
export PREACH_TEMP=$5
export ERLANG_PREFIX=$6

: ${LOGDIR:?} ${EPMD:?} ${PREACH_MACHINE:?} ${PREACH_NODE_NAME:?} ${PREACH_TEMP:?} ${ERLANG_PREFIX:?}

echo Running erlmon on `hostname` as node $PREACH_NODE_NAME > $LOGDIR/`hostname`.info

cleanup()
{
    echo cleaning up >> $LOGDIR/`hostname`.info
    rm -rfv ${PREACH_TEMP}/preachdir.${PREACH_NODE_NAME}  >> $LOGDIR/`hostname`.info
    rm -fv ${PREACH_TEMP}/*.${PREACH_NODE_NAME} >> $LOGDIR/`hostname`.info
}

trap cleanup 0
trap "exit 2" KILL TERM INT ABRT

WORKDIR=${PREACH_TEMP}/preachdir.${PREACH_NODE_NAME}
mkdir $WORKDIR

scp "${PREACH_MACHINE}:${LOGDIR}/setup" $WORKDIR
scp "${PREACH_MACHINE}:${LOGDIR}/*.beam" $WORKDIR 
scp "${PREACH_MACHINE}:${LOGDIR}/*.so" $WORKDIR 
scp "${PREACH_MACHINE}:${LOGDIR}/diskmon" $WORKDIR

cd $WORKDIR
export ERL_EPMD_PORT=$EPMD
export ERL_FULLSWEEP_AFTER=0
nohup ${ERLANG_PREFIX}/bin/erl -pa $WORKDIR +A 10 -kernel net_ticktime 10000000 -sname ${PREACH_NODE_NAME} -detached

nohup $WORKDIR/diskmon >& $LOGDIR/`hostname`.usage 


echo Finished erlmon on `hostname`
