#!/usr/bin/env bash 

echo Running erlmon on `hostname`

export PREACH_MACHINE=$1
export PREACH_NODE_NAME=$2
export LOGDIR=$3
export EPMD=$4
export PREACH_TEMP=$5
export ERLANG_PREFIX=$6

: ${LOGDIR:?} ${EPMD:?} ${PREACH_MACHINE:?} ${PREACH_NODE_NAME:?} ${PREACH_TEMP:?} ${ERLANG_PREFIX:?}

cleanup()
{
  rm -rfv ${PREACH_TEMP}/preachdir.${PREACH_NODE_NAME}* 
  rm -fv ${PREACH_TEMP}/*.${PREACH_NODE_NAME}* 
}

trap cleanup 0
trap "exit 2" 1 2 3 13 15

WORKDIR=${PREACH_TEMP}/preachdir.${PREACH_NODE_NAME}
mkdir $WORKDIR

scp "${PREACH_MACHINE}:${LOGDIR}/setup" $WORKDIR
scp "${PREACH_MACHINE}:${LOGDIR}/*.beam" $WORKDIR 
scp "${PREACH_MACHINE}:${LOGDIR}/*.so" $WORKDIR 
scp "${PREACH_MACHINE}:${LOGDIR}/diskmon" $WORKDIR

cd $WORKDIR
export ERL_EPMD_PORT=$EPMD
export ERL_FULLSWEEP_AFTER=0
nohup ${ERLANG_PREFIX}/bin/erl -pa $WORKDIR +A 10 -sname ${PREACH_NODE_NAME} -detached

nohup $WORKDIR/diskmon >& $LOGDIR/`hostname`.usage 


echo Finished erlmon on `hostname`
