#!/usr/bin/perl -w

#PATH=/bin:/usr/bin:/usr/intel/bin


#[[ -z $NB_PARALLEL_JOB_HOSTS ]] && exit 1

$model = shift @ARGV;

$restargs = join ' ', @ARGV;

#$minspace = $ARGV[1];

print "Running model $model\n";

print "NB_PARALLEL_JOB_HOSTS=$ENV{'NB_PARALLEL_JOB_HOSTS'}\n";

$hosts = $ENV{'NB_PARALLEL_JOB_HOSTS'};

@hostlist = split / /, $hosts;


$PREACH_TIMESTAMP = `date +%s`;
chomp $PREACH_TIMESTAMP;

open HOSTFILE, ">hosts";

$USER = $ENV{USER};

$hostcount = 1;

for $host (@hostlist) {
    print HOSTFILE "$ENV{USER}${PREACH_TIMESTAMP}${hostcount}" . "@" . "$host\n";
    $hostcount++;
}

close HOSTFILE;



#$hosts =~ s/ /,/g;

if (!defined($ENV{PREACH_MACHINE})) {
     print "prun: Using default PREACH_MACHINE.  NFS may have some old files.\n";
     chomp($ENV{PREACH_MACHINE} = `hostname`);
}
print "PREACH_MACHINE = $ENV{PREACH_MACHINE}\n";

if (!defined($ENV{PREACH_SSH})) {
     print "prun: Using default PREACH_SSH.\n";
     $ENV{PREACH_SSH} = "nbjob prun --host";
}
print "PREACH_SSH = $ENV{PREACH_SSH}\n";

if (!defined($ENV{'ERL_EPMD_PORT'})) {
     print "prun: Using default ERL_EPMD_PORT. May collide with other users.\n";
     $ENV{'ERL_EPMD_PORT'} = 4369;
}


if (!defined($ENV{'PREACH_TEMP'})) {
     print "prun: PREACH_TEMP not defined.\n";
     exit(1);
}


if (!defined($ENV{'ERLANG_PREFIX'})) {
     print "prun: ERLANG_PREFIX not defined.\n";
     exit(1);
}

$ENV{'ERL_FULLSWEEP_AFTER'} = 0;

$ORIGDIR = `pwd`;
chomp $ORIGDIR;

$WORKDIR = "$ENV{PREACH_TEMP}/preachdir.${USER}${PREACH_TIMESTAMP}root";
mkdir $WORKDIR;

system "scp $ENV{PREACH_MACHINE}:${ORIGDIR}/*.beam $WORKDIR";
system "scp $ENV{PREACH_MACHINE}:${ORIGDIR}/$model.so $WORKDIR";
system "scp $ENV{PREACH_MACHINE}:${ORIGDIR}/$model.m $WORKDIR";
system "scp $ENV{PREACH_MACHINE}:${ORIGDIR}/erlsetup $WORKDIR";

system "cat hosts >> ../allhosts";

system "rm -f *.usage *.iostat";

system "$WORKDIR/erlsetup $ORIGDIR $ENV{'ERL_EPMD_PORT'} $ENV{PREACH_TEMP} $ENV{ERLANG_PREFIX}";
system "cat bad_servers.txt >> ../allbad";
system "mv bad_servers.txt bad.bak";

system "cp good_servers.txt hosts";
system "echo $ENV{USER}${PREACH_TIMESTAMP}0@`hostname` >> hosts";

system "cp hosts $WORKDIR"; # hosts used by preach to start workers

chdir $WORKDIR;

system "erl -pa $WORKDIR +A 10 -sname $ENV{USER}${PREACH_TIMESTAMP}0 -detached";
system "erl -pa $WORKDIR +A 10 -sname $ENV{USER}${PREACH_TIMESTAMP}root -run preach run -intel -model $model -run init stop -noshell $restargs";


chdir $ORIGDIR;

print "Changing to $ORIGDIR\n";
print "Now in " . `pwd`;

print "PRUN COMPLETE\n";

exit 0;
